### ISSUE TITLE
Hi, I wanna ask how the courses data came from?

### ISSUE THREAD

**Issue by KiRyuWen** [MohimenMG/Learning-management-system#1]
Hey MohimenMG,
I saw your ReadMe, and I looked up Mockaroo. 
However, I can not find courses-related type to generate the mimic data.
Or, maybe I am not signed up for the website, so it doesn't show the private data for me.

Thanks for your consideration. I will be happy if you can answer my silly question.

**Comment by MohimenMG** [comment]
Hey 阿文文,
You may find all the table data in the 1-data folder in CSV format.

For the courses table specifically, it is true there is no dictionary on mockaroo. 

I gave chat GPT a sample data and it generated  the rest of the table as CSV. There is also an AI function on mockaroo you can try.

if you wish to generate the data yourself you will not only have to use mockaroo but also use custom scripts like the ones in the 
2-Notes/data_generation.ipynb file

Mockaroo is great for generating random user names passwords etc, however it will not generate relational tables that satisfy the business logic, 

for example you can generate a table with course names on mockaroo but when it comes to the foreign key program id column it will generate random INT values not the true ids of parent programs 

To solve such problem i created custom scripts that generate tables and their relationships.

hope this helped

**Comment by KiRyuWen** [comment]
Thank you MohimenMG,
I really appreciate you
